Name:           ros-lunar-laser-assembler
Version:        1.7.4
Release:        0%{?dist}
Summary:        ROS laser_assembler package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/laser_assembler
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-filters
Requires:       ros-lunar-laser-geometry
Requires:       ros-lunar-message-filters
Requires:       ros-lunar-message-runtime
Requires:       ros-lunar-pluginlib
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-sensor-msgs
Requires:       ros-lunar-tf
BuildRequires:  ros-lunar-catkin >= 0.5.68
BuildRequires:  ros-lunar-filters
BuildRequires:  ros-lunar-laser-geometry
BuildRequires:  ros-lunar-message-filters
BuildRequires:  ros-lunar-message-generation
BuildRequires:  ros-lunar-pluginlib
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-rostest
BuildRequires:  ros-lunar-sensor-msgs
BuildRequires:  ros-lunar-tf

%description
Provides nodes to assemble point clouds from either LaserScan or PointCloud
messages

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Sun Apr 02 2017 David Gossow <dgossoe@willowgarage.com> - 1.7.4-0
- Autogenerated by Bloom

